### ISSUE TITLE
Добавить query-параметр field в /sensor/<id>/data

### ISSUE THREAD

**Issue by ed-asriyan** [M4MController/controller-web#15]
если передан парамер `field`, то в ответе должно возвращаться только поле, имя которого равно значению параметра `field`, из записей

раньше был такой функционал, но о сломался после перехода на постгрес

**Comment by YAXo-O** [comment]
Из-за ограничений схемы пока любое буду возвращать в формате [{"value": field_value}], где "value" выводится всегда, вне зависимости от того, какой field запрашиваем, field_value - значение запрошенного field. При встрече осудим, как лучше обойти ограничение схемы

**Comment by YAXo-O** [comment]
И ещё - в базе хранится не time_stamp, а timestamp, не помню уже, почему именно (скорее всего time_stamp - ключевое слово postgres), поэтому в manager добавил костыль с проверкой, преобразующий field=time_stamp в field=timestamp

**Comment by ed-asriyan** [comment]
> Из-за ограничений схемы пока любое буду возвращать в формате [{"value": field_value}], где "value" выводится всегда, вне зависимости от того, какой field запрашиваем, field_value - значение запрошенного field. При встрече осудим, как лучше обойти ограничение схемы

так там [dict](https://github.com/M4MController/controller-web/blob/52dfe63791404e76bc5a9923769fca22a77ca666/server/database/schemas.py#L6), в него можно пихать любого вида данные
